version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:13

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - run: npm install @openapitools/openapi-generator-cli -g
      - run: openapi-generator batch \*.yml

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "javascript/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: |
          cd javascript
          npm install
      - run:
          name: Run tests
          command: |
            cd javascript
            npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "javascript/package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm install @openapitools/openapi-generator-cli -g
      - run: openapi-generator batch \*.yml
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: |
            cd javascript
            npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
