version: 2

jobs:
  deploy:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: |
          apk add nodejs
          apk add npm
          apk add openjdk8-jre
          npm install @openapitools/openapi-generator-cli -g
      - run: openapi-generator-cli batch \*.yml
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
      - run: |
          cd javascript
          npm install
      - run:
          name: Publish package
          command: |
            cd javascript
            npm publish --access=public

workflows:
  version: 2
  test-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
