
on: push

name: test

jobs:
  test:
    name: Build @spaceapi/validator-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate OpenAPI client
        run: |
          npm install @openapitools/openapi-generator-cli -g
          openapi-generator-cli batch \*.yml
          cd javascript
          npm install
          npm run build

